#!/usr/bin/env bash
# =============================================================================
# BJ ERP — one-command installer (run on the company server, no internet needed)
#
#   tar xzf bj-erp-installer-<version>.tar.gz && cd bj-erp-installer
#   sudo ./install.sh
#
# What it does:
#   1. checks Docker is available
#   2. loads the bundled container images (images/*.tar)
#   3. asks for the server address + a password for the first admin
#   4. generates all secrets and writes .env
#   5. starts the database, applies every migration + baseline seed
#   6. creates the admin account and starts the whole stack
#   7. exports the HTTPS root certificate for phones to trust
#
# Re-runnable: an existing installation (existing .env + database volume) is
# reused, migrations are replayed idempotently, secrets are NOT regenerated.
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"

say()  { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
fail() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# ── 1. prerequisites ─────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || fail "Docker is not installed. See RUNBOOK.md → Requirements."
docker info >/dev/null 2>&1      || fail "Docker daemon is not running (or you need sudo)."
docker compose version >/dev/null 2>&1 || fail "Docker Compose plugin missing (docker compose)."

# ── 2. load bundled images (offline install) ─────────────────────────────────
if compgen -G "images/*.tar" >/dev/null; then
  say "Loading container images (offline bundle)…"
  for t in images/*.tar; do docker load -i "$t"; done
fi

# Derives APP_ORIGIN (the URL employees type) from APP_HOST + APP_PORT, and
# splits a port off APP_HOST if someone typed "10.10.10.50:3500" — APP_HOST must
# stay a bare hostname/IP because it is the TLS certificate name.
normalise_host_port() {
  case "$APP_HOST" in
    *:*) APP_PORT=${APP_HOST##*:}; APP_HOST=${APP_HOST%:*} ;;
  esac
  APP_PORT=${APP_PORT:-443}
  if [ "$APP_PORT" = "443" ]; then
    APP_ORIGIN="https://${APP_HOST}"
  else
    APP_ORIGIN="https://${APP_HOST}:${APP_PORT}"
  fi
}

# ── 3. install-time inputs ───────────────────────────────────────────────────
if [ -f .env ]; then
  say "Existing .env found — reusing configuration and secrets."
  # shellcheck disable=SC1091
  . ./.env

  # .env files written before the port became configurable have neither
  # APP_PORT nor APP_ORIGIN. Derive and append them so compose can interpolate.
  if ! grep -q '^APP_ORIGIN=' .env; then
    normalise_host_port
    say "Adding APP_PORT/APP_ORIGIN to .env (published on ${APP_PORT})…"
    sed -i "s|^APP_HOST=.*|APP_HOST=${APP_HOST}|" .env
    printf 'APP_PORT=%s\nAPP_ORIGIN=%s\n' "$APP_PORT" "$APP_ORIGIN" >> .env
  fi
else
  DEFAULT_HOST=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
  read -r -p "Server address employees will use (IP or internal domain) [${DEFAULT_HOST:-required}]: " APP_HOST
  APP_HOST=${APP_HOST:-$DEFAULT_HOST}
  [ -n "$APP_HOST" ] || fail "a server address is required"

  read -r -p "HTTPS port to publish [443]: " APP_PORT
  APP_PORT=${APP_PORT:-443}
  normalise_host_port

  while :; do
    read -r -s -p "Password for the first admin account (min 8 chars): " ADMIN_PASSWORD; echo
    [ "${#ADMIN_PASSWORD}" -ge 8 ] && break
    echo "Too short — try again."
  done

  say "Generating secrets…"
  POSTGRES_PASSWORD=$(openssl rand -hex 24)
  JWT_SECRET=$(openssl rand -hex 32)

  # Sign the API keys inside the app image (node is guaranteed there).
  KEYS_JSON=$(docker run --rm --entrypoint node bj-erp-app:latest /gen-keys.mjs "$JWT_SECRET")
  ANON_KEY=$(printf '%s' "$KEYS_JSON" | sed -n 's/.*"anon":"\([^"]*\)".*/\1/p')
  SERVICE_ROLE_KEY=$(printf '%s' "$KEYS_JSON" | sed -n 's/.*"service_role":"\([^"]*\)".*/\1/p')
  [ -n "$ANON_KEY" ] || fail "failed to generate API keys"

  cat > .env <<EOF
# Generated by install.sh $(date -u +%FT%TZ) — keep this file private (chmod 600).
# APP_HOST is the certificate name — bare host, never a port. APP_PORT is what
# the server publishes. APP_ORIGIN is the URL employees type; it is baked into
# the browser bundle, so it must always agree with APP_HOST + APP_PORT.
APP_HOST=${APP_HOST}
APP_PORT=${APP_PORT}
APP_ORIGIN=${APP_ORIGIN}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
APP_VERSION=latest
EOF
  chmod 600 .env
fi

# psql inside the db container as the image's superuser (supabase_admin).
# The image requires password auth even on the local socket — pass it along.
pgexec() {
  docker compose exec -T -e PGPASSWORD="$POSTGRES_PASSWORD" db \
    psql -v ON_ERROR_STOP=1 -U supabase_admin -d postgres "$@"
}

# ── 4. database up + auth schema ─────────────────────────────────────────────
say "Starting the database…"
docker compose up -d db
until docker compose exec -T db pg_isready -U supabase_admin -h localhost >/dev/null 2>&1; do sleep 2; done

say "Starting the auth service (creates/updates its own schema)…"
docker compose up -d auth
for i in $(seq 1 60); do
  if pgexec -tAc \
      "select 1 from information_schema.tables where table_schema='auth' and table_name='users'" \
      2>/dev/null | grep -q 1; then break; fi
  [ "$i" = 60 ] && fail "auth service did not initialise its schema — check: docker compose logs auth"
  sleep 2
done

# ── 5. app schema: migrations + baseline seed ────────────────────────────────
say "Applying database migrations…"
for f in migrations/*.sql; do
  echo "  - $(basename "$f")"
  pgexec -f "/bj/migrations/$(basename "$f")" >/dev/null
done

say "Applying baseline configuration (company, departments, leave types)…"
pgexec -f /bj/seed.sql >/dev/null

# ── 6. first admin + full stack ──────────────────────────────────────────────
if [ -n "${ADMIN_PASSWORD:-}" ]; then
  say "Creating the first admin account (login code: admin)…"
  pgexec -v admin_password="$ADMIN_PASSWORD" -f /bj/bootstrap_admin.sql
fi

say "Starting the application…"
docker compose up -d

# ── 7. HTTPS root certificate for phones ─────────────────────────────────────
say "Exporting the HTTPS root certificate…"
for i in $(seq 1 30); do
  if docker compose exec -T gateway cat /data/caddy/pki/authorities/local/root.crt \
       > bj-root-ca.crt 2>/dev/null && [ -s bj-root-ca.crt ]; then break; fi
  sleep 2
done

cat <<EOF

=============================================================
 BJ ERP is running.

   App:          ${APP_ORIGIN}
   Admin login:  code "admin" + the password you entered

 Employees must type the address above in full, including the
 port — plain http:// on port 80 is not served.

 Phones must trust the certificate once before installing the
 app: copy  bj-root-ca.crt  to each phone and follow
 RUNBOOK.md → "Trusting the certificate on phones".

 Backups, updates, logs: see RUNBOOK.md.
=============================================================
EOF
