#!/usr/bin/env bash
# Install as root-owned /usr/local/sbin/bj-liara-apply. Only this command is sudo-enabled for CI.
set -euo pipefail
umask 077
VERSION=${1:-}
[[ "$VERSION" =~ ^[0-9a-f]{40}$ ]] || { echo 'Expected full commit SHA' >&2; exit 1; }
[ "$(id -u)" = 0 ] && [ "$(cat /etc/bj-liara-target)" = bj-vm ]
ROOT=/opt/bj-erp
INCOMING=/var/lib/bj-deploy/incoming
RELEASE="$ROOT/releases/$VERSION"
exec 8>/run/lock/bj-liara-release.lock
flock -n 8 || { echo 'Another Liara release is running' >&2; exit 1; }
[ "$(df -Pk "$ROOT" | awk 'NR==2 {print $4}')" -ge 5242880 ] || { echo 'Need 5 GiB free' >&2; exit 1; }
for file in "$VERSION.tar" "$VERSION.sha256"; do
  [ -f "$INCOMING/$file" ] && [ ! -L "$INCOMING/$file" ] || exit 1
done
mkdir -p "$RELEASE"
cp "$INCOMING/$VERSION.tar" "$RELEASE/release.tar"
EXPECTED=$(awk '{print $1}' "$INCOMING/$VERSION.sha256")
[[ "$EXPECTED" =~ ^[0-9a-f]{64}$ ]] && [ "$(sha256sum "$RELEASE/release.tar" | cut -d' ' -f1)" = "$EXPECTED" ]
# Reject links, devices, traversal, and unrelated paths before root extraction.
python3 - "$RELEASE/release.tar" "$RELEASE" <<'PY'
import pathlib, sys, tarfile
with tarfile.open(sys.argv[1]) as archive:
    for item in archive.getmembers():
        path = pathlib.PurePosixPath(item.name)
        if path.is_absolute() or '..' in path.parts or not (item.isfile() or item.isdir()):
            raise SystemExit('Unsafe archive member')
        if path.parts and path.parts[0] not in ('stack', 'app-image.tar.gz'):
            raise SystemExit('Unexpected archive member')
        if any(p.startswith('.env') or p in ('backups', '.bj-deploy') for p in path.parts):
            raise SystemExit('Private path in release')
    options = {'filter': 'data'} if hasattr(tarfile, 'data_filter') else {}
    archive.extractall(sys.argv[2], **options)
PY
[ "$(cat "$RELEASE/stack/RELEASE")" = "$VERSION" ]
cd "$ROOT"
if [ -f .env ]; then
  # Automatic application releases must not silently change the database or ingress setup.
  for file in docker-compose.yml docker-compose.liara.yml liara/Caddyfile sql/init/00-init.sh; do
    cmp -s "$file" "$RELEASE/stack/$file" || {
      echo "Infrastructure changed: $file. Apply and validate it explicitly before retrying." >&2
      exit 1
    }
  done
fi
rsync -a "$RELEASE/stack/" "$ROOT/"
mv "$RELEASE/app-image.tar.gz" "$ROOT/bj-erp-app-$VERSION.tar.gz"
export BJ_DEPLOY_TARGET=liara
export BJ_MIGRATIONS_DIR="$RELEASE/stack/migrations" BJ_SEED_FILE="$RELEASE/stack/sql/seed.sql"
if [ ! -f DEPLOYED_RELEASE ]; then
  # Fresh installs only. Existing configuration is never regenerated by a release.
  gunzip -c "bj-erp-app-$VERSION.tar.gz" | docker load
  install -d -m 700 /root/bj-liara
  [ -s /root/bj-liara/admin-password ] || openssl rand -base64 24 > /root/bj-liara/admin-password
  if docker container inspect bj-liara-tls-preflight >/dev/null 2>&1; then
    docker rm -f bj-liara-tls-preflight >/dev/null
  fi
  BJ_APP_HOST=62.60.191.132 BJ_APP_PORT=443 BJ_APP_VERSION="$VERSION" \
    BJ_ADMIN_PASSWORD_FILE=/root/bj-liara/admin-password bash ./install.sh
  rm "bj-erp-app-$VERSION.tar.gz"
else
  bash ./update.sh "$VERSION"
fi
# Public TLS and ingress are part of release success, not merely container startup.
curl --fail --silent --show-error --retry 12 --retry-all-errors --retry-delay 5 \
  --max-time 15 https://62.60.191.132/api/health
printf '%s\n' "$VERSION" > "$ROOT/DEPLOYED_RELEASE"
rm -f "$INCOMING/$VERSION.tar" "$INCOMING/$VERSION.sha256" "$RELEASE/release.tar"
echo "Liara release verified: $VERSION"
