#!/usr/bin/env bash
# Shared deployment helpers. This file is sourced by both macOS Bash 3.2 and
# Linux Bash, so do not use associative arrays, mapfile, or Bash 4-only syntax.

BJ_PROJECT_NAME="${BJ_PROJECT_NAME:-bj-erp}"

bj_say()  { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
bj_warn() { printf '\033[1;33m%s\033[0m\n' "$*" >&2; }
bj_fail() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; return 1; }

bj_require_command() {
  command -v "$1" >/dev/null 2>&1 || bj_fail "required command is missing: $1"
}

bj_validate_version() {
  case "${1:-}" in
    ''|*[!A-Za-z0-9._-]*) bj_fail "invalid version '$1'"; return 1 ;;
  esac
  [ "${#1}" -le 64 ] || { bj_fail "version is longer than 64 characters"; return 1; }
}

bj_validate_run_id() {
  case "${1:-}" in
    ''|*[!A-Za-z0-9._-]*) bj_fail "invalid run id '$1'"; return 1 ;;
  esac
  [ "${#1}" -le 80 ] || { bj_fail "run id is longer than 80 characters"; return 1; }
}

bj_validate_host() {
  case "${1:-}" in
    ''|*[!A-Za-z0-9.-]*) bj_fail "host must contain only letters, digits, dots, and dashes"; return 1 ;;
  esac
}

bj_validate_port() {
  case "${1:-}" in ''|*[!0-9]*) bj_fail "port must be a number"; return 1 ;; esac
  [ "$1" -ge 1 ] 2>/dev/null && [ "$1" -le 65535 ] 2>/dev/null \
    || { bj_fail "port must be from 1 to 65535"; return 1; }
}

bj_resolve_remote_backup_path() {
  # Maps the backup path a server recorded for a run onto the exact absolute
  # path the controller is willing to download, or refuses it.
  #
  #   bj_resolve_remote_backup_path /home/user/installer ./backups/pre-x.dump
  #     -> /home/user/installer/backups/pre-x.dump
  #
  # update.sh runs with the installer directory as its working directory, so
  # older runs recorded a directory-relative path. rsync would resolve that
  # against the SSH user's home instead, and the file name reaches a remote
  # shell, so the name is reduced to a single safe component: no traversal, no
  # nesting, no leading dash, no shell metacharacter, no absolute path outside
  # the run's own backup directory.
  local remote_dir="${1:-}" recorded="${2:-}" name
  case "$remote_dir" in
    /*) ;;
    *) bj_fail "remote directory must be an absolute path"; return 1 ;;
  esac
  remote_dir="${remote_dir%/}"
  case "$recorded" in
    "$remote_dir"/backups/*) name="${recorded#"$remote_dir"/backups/}" ;;
    ./backups/*)             name="${recorded#./backups/}" ;;
    backups/*)               name="${recorded#backups/}" ;;
    *) bj_fail "server returned an unexpected backup path: $recorded"; return 1 ;;
  esac
  case "$name" in
    ''|.|..|-*|*/*|*[!A-Za-z0-9._-]*)
      bj_fail "server returned an unsafe backup file name: $recorded"; return 1 ;;
  esac
  [ "${#name}" -le 200 ] \
    || { bj_fail "server returned an over-long backup file name"; return 1; }
  printf '%s/backups/%s\n' "$remote_dir" "$name"
}

bj_hash_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

bj_file_size() {
  if stat -f '%z' "$1" >/dev/null 2>&1; then
    stat -f '%z' "$1"
  else
    stat -c '%s' "$1"
  fi
}

bj_atomic_write() {
  # Usage: printf 'value\n' | bj_atomic_write path
  local destination="$1" temporary
  temporary="${destination}.tmp.$$"
  umask 077
  dd of="$temporary" 2>/dev/null
  mv -f "$temporary" "$destination"
}

bj_make_run_id() {
  local suffix
  suffix=$(openssl rand -hex 3 2>/dev/null || printf '%06d' "$$")
  date -u '+%Y%m%dT%H%M%SZ-'"$suffix"
}

bj_arch_name() {
  case "$1" in
    arm64|aarch64) printf 'arm64\n' ;;
    amd64|x86_64) printf 'amd64\n' ;;
    *) printf '%s\n' "$1" ;;
  esac
}

bj_require_arch() {
  local actual expected label
  actual=$(bj_arch_name "$1")
  expected=$(bj_arch_name "$2")
  label="${3:-target}"
  [ "$actual" = "$expected" ] \
    || { bj_fail "$label architecture is '$actual'; expected '$expected'"; return 1; }
}

bj_env_value() {
  # Reads a simple KEY=value file without sourcing it. Values generated by this
  # project contain no shell syntax; this keeps read-only inspection safer.
  local key="$1" file="$2"
  sed -n "s/^${key}=//p" "$file" | tail -n 1
}

bj_env_set() {
  local file="$1" key="$2" value="$3" temporary
  case "$key" in ''|*[!A-Z0-9_]*) bj_fail "invalid environment key"; return 1 ;; esac
  case "$value" in *$'\n'*|*$'\r'*) bj_fail "environment value must be one line"; return 1 ;; esac
  temporary="${file}.tmp.$$"
  umask 077
  if [ -f "$file" ]; then
    awk -v key="$key" -v value="$value" \
      'BEGIN { done=0 } $0 ~ "^" key "=" { if (!done) print key "=" value; done=1; next } { print } END { if (!done) print key "=" value }' \
      "$file" > "$temporary"
  else
    printf '%s=%s\n' "$key" "$value" > "$temporary"
  fi
  chmod 600 "$temporary"
  mv -f "$temporary" "$file"
}

bj_set_app_version() {
  # Docker Compose gives an exported shell variable precedence over values in
  # .env. Update both sources together so a long-running deployment shell
  # cannot recreate the app with the stale tag it loaded during preflight.
  local file="$1" version="$2"
  bj_validate_version "$version" || return 1
  bj_env_set "$file" APP_VERSION "$version" || return 1
  APP_VERSION="$version"
  export APP_VERSION
}

bj_confirm_phrase() {
  local expected="$1" answer
  printf 'Type exactly: %s\n> ' "$expected" >&2
  IFS= read -r answer
  [ "$answer" = "$expected" ] \
    || { bj_fail "confirmation did not match; nothing was changed"; return 1; }
}

bj_compose_init() {
  # Sets BJ_COMPOSE_ROOT/BJ_COMPOSE_TARGET. bj_compose passes both files every
  # time, which prevents an operator from accidentally omitting an overlay.
  BJ_COMPOSE_ROOT="$1"
  BJ_COMPOSE_TARGET="$2"
  case "$BJ_COMPOSE_TARGET" in
    local)  BJ_COMPOSE_OVERLAY="$BJ_COMPOSE_ROOT/docker-compose.local-arm64.yml" ;;
    client) BJ_COMPOSE_OVERLAY="$BJ_COMPOSE_ROOT/docker-compose.client-amd64.yml" ;;
    *) bj_fail "unknown Compose target '$BJ_COMPOSE_TARGET'"; return 1 ;;
  esac
  [ -f "$BJ_COMPOSE_ROOT/docker-compose.yml" ] || { bj_fail "base Compose file missing"; return 1; }
  [ -f "$BJ_COMPOSE_OVERLAY" ] || { bj_fail "Compose overlay missing: $BJ_COMPOSE_OVERLAY"; return 1; }
  export BJ_COMPOSE_ROOT BJ_COMPOSE_TARGET BJ_COMPOSE_OVERLAY
}

bj_compose() {
  docker compose --project-name "$BJ_PROJECT_NAME" \
    --project-directory "$BJ_COMPOSE_ROOT" \
    -f "$BJ_COMPOSE_ROOT/docker-compose.yml" \
    -f "$BJ_COMPOSE_OVERLAY" "$@"
}

bj_compose_with_db_password() {
  # Pass only the environment VARIABLE NAME to Docker/Compose. The secret is
  # inherited by the short-lived process and never appears in command argv.
  local rc=0
  [ -n "${POSTGRES_PASSWORD:-}" ] || { bj_fail "POSTGRES_PASSWORD is not loaded"; return 1; }
  export PGPASSWORD="$POSTGRES_PASSWORD"
  bj_compose exec -T -e PGPASSWORD "$@" || rc=$?
  unset PGPASSWORD
  return "$rc"
}
