#!/usr/bin/env bash
# Regenerate supabase/schema.sql: the current definition of every table, view,
# function, policy and grant in the app's own schemas (public and private).
#
# Migrations are history. A function can be redefined in several of them and
# only the last definition runs, so read schema.sql for what is live today.
# It is dumped from the local Docker database: apply a new migration there
# first, then run this and commit the output together with the migration.
#
#   npm run schema:dump
#   BJ_DB_CONTAINER=<name> npm run schema:dump   # default: bj-erp-db-1
set -euo pipefail
cd "$(dirname "$0")/.."

container=${BJ_DB_CONTAINER:-bj-erp-db-1}
out=supabase/schema.sql
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
  printf -- '-- GENERATED by scripts/dump-schema.sh from the local database. Do not edit.\n'
  printf -- '-- Current state of the public and private schemas; supabase/migrations/ is the history.\n\n'
  docker exec "$container" sh -c \
    'PGPASSWORD="$POSTGRES_PASSWORD" pg_dump -h localhost -U supabase_admin -d postgres --schema-only --no-owner --schema=public --schema=private'
} > "$tmp"

mv "$tmp" "$out"
chmod 644 "$out"
printf 'Wrote %s (%s lines)\n' "$out" "$(wc -l < "$out" | tr -d ' ')"
