/**
 * Maps raw Postgres/PostgREST error messages (stable English strings raised by
 * our SECURITY DEFINER functions, plus constraint violations) to localized
 * fa/en user-facing messages. Server-only — call from server actions.
 *
 * Unknown errors are logged server-side and replaced with a generic message so
 * internals never leak to the UI. If translation itself fails (no request
 * locale), the raw message is returned as a last resort.
 */

import { getTranslations } from 'next-intl/server';

/**
 * Form fields an error can be attached to, so the UI renders it beside the
 * offending input instead of in the page-level banner.
 *
 * The mapping lives on the RULE, not at the call site: this module is the one
 * place that knows which raw database message means which field, so a future
 * action raising the same message gets the same placement for free.
 */
export type ErrorField = 'personnel_no';

/** The shape every failing server action returns. `field` is optional. */
export type DbErrorResult = { ok: false; error: string; field?: ErrorField };

type Rule = {
  re: RegExp;
  key: string;
  params?: (m: RegExpMatchArray) => Record<string, string | number>;
  field?: ErrorField;
};

const RULES: Rule[] = [
  {
    // The minute-contract migrations retained the legacy "day(s)" word in
    // some SQL messages, but both numeric values are now minutes.
    re: /insufficient balance: ([\d.]+) (?:day|minute)\(s\) requested, ([\d.]+) available/,
    key: 'insufficientBalanceMinutes',
    params: (m) => ({ requested: m[1], available: m[2] }),
  },
  { re: /account is inactive/i, key: 'accountInactive' },
  { re: /employee not found/i, key: 'employeeNotFound' },
  { re: /select between 1 and 100 employees/i, key: 'employeeSelectionLimit' },
  { re: /invalid work hours or hourly leave cap/i, key: 'invalidHourlySettings' },
  { re: /holiday not found/i, key: 'holidayNotFound' },
  { re: /overlapping approved leave exists/, key: 'overlapApproved' },
  { re: /overlapping leave request exists/, key: 'overlap' },
  { re: /requested days must be greater than 0/, key: 'zeroDays' },
  { re: /invalid or inactive leave type/, key: 'invalidLeaveType' },
  { re: /date range too long/, key: 'rangeTooLong' },
  // Raised by `jalali_month_of` when a request's date falls outside the seeded
  // `jalali_months` table (currently 1400-1450 = 2021-03-21 .. 2072-03-19).
  // Until 2026-08-18 this was UNMAPPED, so back-dating a request before Farvardin
  // 1400 produced the generic "unexpected error" and told the person nothing.
  //
  // NOTE: the translated message names Farvardin 1400. If `jalali_months` is ever
  // widened (it is generated by scripts/gen-jalali-months.mjs, so widening is
  // cheap), update `dbErrors.dateOutOfCalendarRange` in messages/{fa,en}.json to
  // match — a stale boundary in an error message is its own small trap.
  { re: /date outside supported calendar range/i, key: 'dateOutOfCalendarRange' },
  { re: /start and end dates are required/, key: 'datesRequired' },
  { re: /signature authorization is required/, key: 'signatureAuthorizationRequired' },
  { re: /signature is required/, key: 'signatureRequired' },
  { re: /signature data is invalid/, key: 'signatureInvalid' },
  { re: /request signature not found/, key: 'signatureNotFound' },
  { re: /request was already decided/, key: 'alreadyDecided' },
  // FR-36 approval chain.
  { re: /you have already signed this request/, key: 'alreadySignedByYou' },
  { re: /an earlier approval is still required/, key: 'earlierApprovalRequired' },
  { re: /approval step order must be between/, key: 'approvalStepOrderInvalid' },
  { re: /approval step not found/, key: 'approvalStepNotFound' },
  // FR-42 approval steps by role or named person.
  { re: /invalid approval step role/i, key: 'invalidApprovalStepRole' },
  { re: /this step must name a person|approval_steps_employee_needs_person/i, key: 'approvalStepNeedsPerson' },
  { re: /approval step was not saved/i, key: 'approvalStepNotSaved' },
  { re: /duplicate key value.*approval_steps_company_(role|person)_uniq/, key: 'duplicateApprovalStep' },
  { re: /duplicate key value.*leave_request_approvals_uniq/, key: 'alreadySignedByYou' },
  { re: /only pending requests can be/, key: 'onlyPending' },
  { re: /only pending or not-yet-started approved requests/, key: 'cannotCancel' },
  { re: /request not found/, key: 'requestNotFound' },
  { re: /current password is incorrect/, key: 'wrongCurrentPassword' },
  { re: /new password must be at least 8 characters/, key: 'passwordTooShort' },
  { re: /new password must be at most 72 ASCII characters/, key: 'passwordTooLong' },
  { re: /invalid employee code/, key: 'invalidEmployeeCode' },
  { re: /employee code already exists/, key: 'duplicateEmployeeCode' },
  { re: /duplicate key value.*profiles_employee_code/, key: 'duplicateEmployeeCode' },
  // The personnel number is what the Add Employee form actually collects — the
  // employee code is derived from it (FR-31). Both of these raised messages were
  // UNMAPPED until 2026-08-18, so a duplicate personnel number reached the user
  // as the generic "unexpected error" fallback with no hint of what was wrong.
  {
    re: /personnel number already exists/,
    key: 'duplicatePersonnelNo',
    field: 'personnel_no',
  },
  // Not redundant with the rule above: `create_employee_impl`'s `exists` test is
  // a pre-check, and two concurrent creates still race to this unique index. The
  // path that actually enforces uniqueness needs its own user-facing message.
  {
    re: /duplicate key value.*profiles_company_personnel_no_key/,
    key: 'duplicatePersonnelNo',
    field: 'personnel_no',
  },
  {
    re: /invalid personnel number/,
    key: 'invalidPersonnelNo',
    field: 'personnel_no',
  },
  { re: /duplicate key value.*holidays_company_date/, key: 'duplicateHoliday' },
  { re: /duplicate key value.*departments_company_code_key/, key: 'duplicateDepartmentCode' },
  // createDepartment auto-generates the code and retries a bounded number of
  // times; exhausting them means every candidate was taken.
  { re: /could not generate a unique department code/, key: 'duplicateDepartmentCode' },
  { re: /invalid department code|departments_code_format/, key: 'invalidDepartmentCode' },
  { re: /department name is required/, key: 'departmentNameRequired' },
  { re: /cannot remove your own admin role/, key: 'cannotRemoveOwnAdmin' },
  { re: /cannot deactivate the last active admin/, key: 'cannotDeactivateLastAdmin' },
  { re: /employee cannot be their own manager|profiles_manager_not_self/i, key: 'managerCannotBeSelf' },
  { re: /no profile for caller/, key: 'noProfile' },
  { re: /allocation days must be greater than 0/, key: 'allocationInvalid' },
  // FR-43: HR may set an opening balance and accrual policy, but not their own.
  { re: /you cannot change your own leave balance/i, key: 'cannotSetOwnBalance' },
  { re: /this leave type cannot be taken hourly/, key: 'hourlyNotAllowed' },
  { re: /end time must be after start time/, key: 'endBeforeStart' },
  { re: /times must fall within working hours/, key: 'outsideWorkHours' },
  { re: /hourly leave exceeds the daily limit/, key: 'hourlyDailyLimit' },
  // Errand (FR-30). The form validates both client-side first, so these only
  // surface when the DB is reached directly or the client check is bypassed.
  { re: /errand location is required/, key: 'errandLocationRequired' },
  { re: /errand location is too long/, key: 'errandLocationTooLong' },
  // Should be unreachable — the serial index is keyed by kind since
  // 20260730130001. Mapped anyway: when it DID fire, the worker saw only the
  // generic "unexpected error" and had nothing to report.
  { re: /duplicate key value.*leave_requests_serial_uniq/, key: 'serialCollision' },
  { re: /replacement must be an active colleague in your department/, key: 'replacementNotColleague' },
  { re: /replacement is on leave during this period/, key: 'replacementAway' },
  { re: /target balance must be >= 0/, key: 'balanceNegative' },
  { re: /at least one working day is required/i, key: 'allWeekWeekend' },
  { re: /invalid weekend days/i, key: 'invalidWeekend' },
  { re: /a reference date is required for every-other-week days/i, key: 'weekendAnchorRequired' },
  { re: /a day cannot be both weekly and every-other-week/i, key: 'weekendOverlap' },
  { re: /holiday date and farsi name are required/i, key: 'holidayFieldsRequired' },
  // FR-40 bulk holiday import.
  { re: /no holidays to import/i, key: 'holidayImportEmpty' },
  { re: /too many holidays in one import/i, key: 'holidayImportTooMany' },
  { re: /duplicate holiday date in import/i, key: 'holidayImportDuplicate' },
  { re: /holiday name is too long/i, key: 'holidayNameTooLong' },
  { re: /holidays were not saved/i, key: 'holidayImportNotSaved' },
  { re: /not allowed to review requests/i, key: 'notAllowedToReview' },
  { re: /not allowed to|only admins can|not permitted|admin role required|admin or manager role required|admin or hr role required|only admins or hr can/i, key: 'notAllowed' },
  { re: /not authenticated/i, key: 'notAuthenticated' },
];

export async function localizeDbError(raw: string): Promise<string> {
  let t: Awaited<ReturnType<typeof getTranslations>>;
  try {
    t = await getTranslations('dbErrors');
  } catch {
    return raw;
  }
  for (const rule of RULES) {
    const m = raw.match(rule.re);
    if (m) return t(rule.key, rule.params?.(m));
  }
  console.error('[db-error] unmapped:', raw);
  return t('unexpected');
}

/**
 * The form field a raw database message belongs to, or undefined when it is a
 * page-level problem. Exported for unit tests; `dbErr` is the normal caller.
 */
export function fieldForDbError(raw: string): ErrorField | undefined {
  // The FIRST matching rule, not the first field-carrying one. `localizeDbError`
  // takes the first match too, and the two must agree — otherwise a message
  // produced by rule 3 could be placed by rule 9's field, putting the wrong text
  // under the input.
  return RULES.find((rule) => rule.re.test(raw))?.field;
}

/**
 * Shorthand for action error results: `return dbErr(error.message)`.
 *
 * `field` is additive — every existing caller reads only `.error` and is
 * unaffected, and any result without a field keeps rendering in the banner.
 */
export async function dbErr(raw: string): Promise<DbErrorResult> {
  return {
    ok: false as const,
    error: await localizeDbError(raw),
    field: fieldForDbError(raw),
  };
}
