import { describe, it, expect } from 'vitest';
import { planAccruals } from '@/lib/leave/accrual';
import type { AccrualPolicy, JalaliMonth } from '@/lib/leave/accrual';

// Real Jalali months around the 1404→1405 boundary, as generated by plan 1's
// jalali_months table (verified against it, not invented).
const MONTHS: JalaliMonth[] = [
  { jalaliYear: 1404, jalaliMonth: 12, gregorianStart: '2026-02-20', gregorianEnd: '2026-03-20' },
  { jalaliYear: 1405, jalaliMonth: 1, gregorianStart: '2026-03-21', gregorianEnd: '2026-04-20' },
  { jalaliYear: 1405, jalaliMonth: 2, gregorianStart: '2026-04-21', gregorianEnd: '2026-05-21' },
  { jalaliYear: 1405, jalaliMonth: 3, gregorianStart: '2026-05-22', gregorianEnd: '2026-06-21' },
];

const POLICY: AccrualPolicy = {
  accrualMinutesPerMonth: 480, // 1 day at 8h
  annualCapMinutes: 5760, // 12 days
  carryoverCapMinutes: 4320, // 9 days
  accrualStartMonth: '2026-03-21',
};

const base = {
  policy: POLICY,
  months: MONTHS,
  posted: [],
  hireDate: null,
  today: '2026-06-01',
  openingBalanceMinutes: 0,
};

describe('planAccruals', () => {
  it('posts one row per due month, with a running balance', () => {
    const rows = planAccruals(base);
    expect(rows.map((r) => r.periodMonth)).toEqual(['2026-03-21', '2026-04-21', '2026-05-22']);
    expect(rows.map((r) => r.deltaMinutes)).toEqual([480, 480, 480]);
    expect(rows.map((r) => r.balanceAfterMinutes)).toEqual([480, 960, 1440]);
    expect(rows.every((r) => r.entryType === 'allocation')).toBe(true);
  });

  it('starts from the opening balance', () => {
    const rows = planAccruals({ ...base, openingBalanceMinutes: 2400 });
    expect(rows[0].balanceAfterMinutes).toBe(2880);
  });

  it('is idempotent: already-posted months are skipped', () => {
    const rows = planAccruals({
      ...base,
      posted: [
        { periodMonth: '2026-03-21', entryType: 'allocation', deltaMinutes: 480 },
        { periodMonth: '2026-04-21', entryType: 'allocation', deltaMinutes: 480 },
      ],
      openingBalanceMinutes: 960,
    });
    expect(rows.map((r) => r.periodMonth)).toEqual(['2026-05-22']);
    expect(rows[0].balanceAfterMinutes).toBe(1440);
  });

  it('posts nothing when everything is already posted', () => {
    const posted = MONTHS.slice(1, 4).map((m) => ({
      periodMonth: m.gregorianStart,
      entryType: 'allocation' as const,
      deltaMinutes: 480,
    }));
    expect(planAccruals({ ...base, posted, openingBalanceMinutes: 1440 })).toEqual([]);
  });

  it('does not post months beyond today', () => {
    const rows = planAccruals({ ...base, today: '2026-04-25' });
    expect(rows.map((r) => r.periodMonth)).toEqual(['2026-03-21', '2026-04-21']);
  });

  it('skips months that ended before the hire date', () => {
    const rows = planAccruals({ ...base, hireDate: '2026-04-21' });
    expect(rows.map((r) => r.periodMonth)).toEqual(['2026-04-21', '2026-05-22']);
  });

  it('pro-rates the hire month by calendar days', () => {
    // Hired 2026-05-07, inside 1405-02 (2026-04-21..2026-05-21, 31 days).
    // Days from hire through month end = 15. round(480 * 15 / 31) = 232.
    const rows = planAccruals({ ...base, hireDate: '2026-05-07' });
    expect(rows[0].periodMonth).toBe('2026-04-21');
    expect(rows[0].deltaMinutes).toBe(232);
    expect(rows[1].deltaMinutes).toBe(480);
  });

  it('clamps accruals to the annual cap within a Jalali year', () => {
    const rows = planAccruals({
      ...base,
      policy: { ...POLICY, annualCapMinutes: 1000 },
    });
    expect(rows.map((r) => r.deltaMinutes)).toEqual([480, 480, 40]);
    expect(rows[2].balanceAfterMinutes).toBe(1000);
  });

  it('counts already-posted accruals against the annual cap', () => {
    const rows = planAccruals({
      ...base,
      policy: { ...POLICY, annualCapMinutes: 1000 },
      posted: [{ periodMonth: '2026-03-21', entryType: 'allocation', deltaMinutes: 480 }],
      openingBalanceMinutes: 480,
    });
    expect(rows.map((r) => r.deltaMinutes)).toEqual([480, 40]);
  });

  it('ignores the annual cap when it is null', () => {
    const rows = planAccruals({ ...base, policy: { ...POLICY, annualCapMinutes: null } });
    expect(rows.map((r) => r.deltaMinutes)).toEqual([480, 480, 480]);
  });

  it('forfeits the excess above the carryover cap at Farvardin 1', () => {
    // Accrual started the previous year, so a year boundary is crossed carrying
    // 6000 minutes against a 4320 cap: forfeit 1680 before crediting Farvardin.
    const rows = planAccruals({
      ...base,
      policy: { ...POLICY, accrualStartMonth: '2026-02-20' },
      posted: [{ periodMonth: '2026-02-20', entryType: 'allocation', deltaMinutes: 480 }],
      openingBalanceMinutes: 6000,
      today: '2026-04-01',
    });
    expect(rows[0]).toMatchObject({
      periodMonth: '2026-03-21',
      entryType: 'carryover_forfeit',
      deltaMinutes: -1680,
      balanceAfterMinutes: 4320,
    });
    expect(rows[1]).toMatchObject({
      periodMonth: '2026-03-21',
      entryType: 'allocation',
      deltaMinutes: 480,
      balanceAfterMinutes: 4800,
    });
  });

  it('does not forfeit when the balance is under the cap', () => {
    const rows = planAccruals({
      ...base,
      policy: { ...POLICY, accrualStartMonth: '2026-02-20' },
      posted: [{ periodMonth: '2026-02-20', entryType: 'allocation', deltaMinutes: 480 }],
      openingBalanceMinutes: 1000,
      today: '2026-04-01',
    });
    expect(rows.every((r) => r.entryType === 'allocation')).toBe(true);
  });

  it('does not forfeit on the very first accrual month, even if it is Farvardin', () => {
    const rows = planAccruals({ ...base, openingBalanceMinutes: 9999, today: '2026-04-01' });
    expect(rows).toHaveLength(1);
    expect(rows[0].entryType).toBe('allocation');
  });

  it('never re-posts a forfeiture that already exists', () => {
    const rows = planAccruals({
      ...base,
      policy: { ...POLICY, accrualStartMonth: '2026-02-20' },
      posted: [
        { periodMonth: '2026-02-20', entryType: 'allocation', deltaMinutes: 480 },
        { periodMonth: '2026-03-21', entryType: 'carryover_forfeit', deltaMinutes: -1680 },
        { periodMonth: '2026-03-21', entryType: 'allocation', deltaMinutes: 480 },
      ],
      openingBalanceMinutes: 4800,
      today: '2026-04-01',
    });
    expect(rows).toEqual([]);
  });

  it('posts nothing when the rate is zero (sick leave)', () => {
    expect(planAccruals({ ...base, policy: { ...POLICY, accrualMinutesPerMonth: 0 } })).toEqual([]);
  });
});
