// Generated by Supabase (`supabase gen types typescript`). Do not edit by hand.
// Regenerate after schema changes. Source of truth: supabase/migrations/*.sql
//
// EXCEPTION (2026-07-29, leave v2): the minutes columns, work_settings.hours_per_day,
// jalali_months, and jalali_month_of were added BY HAND. `supabase gen types` pulls
// public.ecr.aws/supabase/postgres-meta at runtime, and that image cannot be fetched
// from Iran (same constraint that made server-side Docker builds impossible — see
// docs/MEMORY.md). The CLI is in devDependencies for machines that can reach it.
// Verified instead by `npm run build`: every column here is exercised by typed
// call sites, so a wrong name or type fails the build rather than reaching runtime.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          after: Json | null
          before: Json | null
          created_at: string
          entity: string
          entity_id: string | null
          id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity: string
          entity_id?: string | null
          id?: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          entity?: string
          entity_id?: string | null
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      companies: {
        Row: {
          created_at: string
          id: string
          name: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
        }
        Relationships: []
      }
      departments: {
        Row: {
          code: string
          company_id: string
          created_at: string
          id: string
          kind: Database["public"]["Enums"]["department_kind"]
          manager_id: string | null
          name_en: string
          name_fa: string
        }
        Insert: {
          code: string
          company_id: string
          created_at?: string
          id?: string
          kind: Database["public"]["Enums"]["department_kind"]
          manager_id?: string | null
          name_en: string
          name_fa: string
        }
        Update: {
          code?: string
          company_id?: string
          created_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["department_kind"]
          manager_id?: string | null
          name_en?: string
          name_fa?: string
        }
        Relationships: [
          {
            foreignKeyName: "departments_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "departments_manager_id_fkey"
            columns: ["manager_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      employee_leave_policies: {
        Row: {
          accrual_minutes_per_month: number
          accrual_start_month: string
          annual_cap_minutes: number | null
          carryover_cap_minutes: number
          created_at: string
          created_by: string | null
          employee_id: string
          id: string
          leave_type_id: string
          updated_at: string
        }
        Insert: {
          accrual_minutes_per_month?: number
          accrual_start_month: string
          annual_cap_minutes?: number | null
          carryover_cap_minutes?: number
          created_at?: string
          created_by?: string | null
          employee_id: string
          id?: string
          leave_type_id: string
          updated_at?: string
        }
        Update: {
          accrual_minutes_per_month?: number
          accrual_start_month?: string
          annual_cap_minutes?: number | null
          carryover_cap_minutes?: number
          created_at?: string
          created_by?: string | null
          employee_id?: string
          id?: string
          leave_type_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "employee_leave_policies_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employee_leave_policies_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "employee_leave_policies_leave_type_id_fkey"
            columns: ["leave_type_id"]
            isOneToOne: false
            referencedRelation: "leave_types"
            referencedColumns: ["id"]
          },
        ]
      }
      holidays: {
        Row: {
          company_id: string
          created_at: string
          holiday_date: string
          id: string
          is_recurring: boolean
          name_en: string | null
          name_fa: string
        }
        Insert: {
          company_id: string
          created_at?: string
          holiday_date: string
          id?: string
          is_recurring?: boolean
          name_en?: string | null
          name_fa: string
        }
        Update: {
          company_id?: string
          created_at?: string
          holiday_date?: string
          id?: string
          is_recurring?: boolean
          name_en?: string | null
          name_fa?: string
        }
        Relationships: [
          {
            foreignKeyName: "holidays_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      jalali_months: {
        Row: {
          gregorian_end: string
          gregorian_start: string
          jalali_month: number
          jalali_year: number
        }
        Insert: {
          gregorian_end: string
          gregorian_start: string
          jalali_month: number
          jalali_year: number
        }
        Update: {
          gregorian_end?: string
          gregorian_start?: string
          jalali_month?: number
          jalali_year?: number
        }
        Relationships: []
      }
      leave_allocations: {
        Row: {
          allocated_minutes: number
          created_at: string
          created_by: string | null
          employee_id: string
          id: string
          leave_type_id: string
          period_end: string
          period_start: string
        }
        Insert: {
          allocated_minutes: number
          created_at?: string
          created_by?: string | null
          employee_id: string
          id?: string
          leave_type_id: string
          period_end: string
          period_start: string
        }
        Update: {
          allocated_minutes?: number
          created_at?: string
          created_by?: string | null
          employee_id?: string
          id?: string
          leave_type_id?: string
          period_end?: string
          period_start?: string
        }
        Relationships: [
          {
            foreignKeyName: "leave_allocations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_allocations_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_allocations_leave_type_id_fkey"
            columns: ["leave_type_id"]
            isOneToOne: false
            referencedRelation: "leave_types"
            referencedColumns: ["id"]
          },
        ]
      }
      leave_ledger: {
        Row: {
          balance_after_minutes: number
          created_at: string
          delta_minutes: number
          employee_id: string
          entry_type: Database["public"]["Enums"]["ledger_entry"]
          id: string
          leave_type_id: string
          note: string | null
          period_month: string | null
          request_id: string | null
          seq: number
        }
        Insert: {
          balance_after_minutes: number
          created_at?: string
          delta_minutes: number
          employee_id: string
          entry_type: Database["public"]["Enums"]["ledger_entry"]
          id?: string
          leave_type_id: string
          note?: string | null
          period_month?: string | null
          request_id?: string | null
          seq?: number
        }
        Update: {
          balance_after_minutes?: number
          created_at?: string
          delta_minutes?: number
          employee_id?: string
          entry_type?: Database["public"]["Enums"]["ledger_entry"]
          id?: string
          leave_type_id?: string
          note?: string | null
          period_month?: string | null
          request_id?: string | null
          seq?: number
        }
        Relationships: [
          {
            foreignKeyName: "leave_ledger_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_ledger_leave_type_id_fkey"
            columns: ["leave_type_id"]
            isOneToOne: false
            referencedRelation: "leave_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_ledger_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "leave_requests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_ledger_request_id_fkey"
            columns: ["request_id"]
            isOneToOne: false
            referencedRelation: "team_leave_calendar"
            referencedColumns: ["id"]
          },
        ]
      }
      leave_requests: {
        Row: {
          created_at: string
          day_part: Database["public"]["Enums"]["day_part"]
          decided_at: string | null
          decided_by: string | null
          decision_note: string | null
          employee_id: string
          end_date: string
          end_time: string | null
          id: string
          leave_type_id: string
          reason: string | null
          replacement_id: string | null
          requested_minutes: number
          start_date: string
          start_time: string | null
          status: Database["public"]["Enums"]["leave_status"]
          unit: Database["public"]["Enums"]["leave_unit"]
        }
        Insert: {
          created_at?: string
          day_part?: Database["public"]["Enums"]["day_part"]
          decided_at?: string | null
          decided_by?: string | null
          decision_note?: string | null
          employee_id: string
          end_date: string
          end_time?: string | null
          id?: string
          leave_type_id: string
          reason?: string | null
          replacement_id?: string | null
          requested_minutes: number
          start_date: string
          start_time?: string | null
          status?: Database["public"]["Enums"]["leave_status"]
          unit?: Database["public"]["Enums"]["leave_unit"]
        }
        Update: {
          created_at?: string
          day_part?: Database["public"]["Enums"]["day_part"]
          decided_at?: string | null
          decided_by?: string | null
          decision_note?: string | null
          employee_id?: string
          end_date?: string
          end_time?: string | null
          id?: string
          leave_type_id?: string
          reason?: string | null
          replacement_id?: string | null
          requested_minutes?: number
          start_date?: string
          start_time?: string | null
          status?: Database["public"]["Enums"]["leave_status"]
          unit?: Database["public"]["Enums"]["leave_unit"]
        }
        Relationships: [
          {
            foreignKeyName: "leave_requests_decided_by_fkey"
            columns: ["decided_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_requests_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_requests_leave_type_id_fkey"
            columns: ["leave_type_id"]
            isOneToOne: false
            referencedRelation: "leave_types"
            referencedColumns: ["id"]
          },
        ]
      }
      leave_types: {
        Row: {
          active: boolean
          affects_balance: boolean
          allow_half_day: boolean
          allow_hourly: boolean
          color: string | null
          company_id: string
          default_accrual_minutes_per_month: number | null
          default_annual_cap_minutes: number | null
          default_annual_quota_days: number | null
          default_carryover_cap_minutes: number
          id: string
          is_paid: boolean
          name_en: string | null
          name_fa: string
        }
        Insert: {
          active?: boolean
          affects_balance?: boolean
          allow_half_day?: boolean
          allow_hourly?: boolean
          color?: string | null
          company_id: string
          default_accrual_minutes_per_month?: number | null
          default_annual_cap_minutes?: number | null
          default_annual_quota_days?: number | null
          default_carryover_cap_minutes?: number
          id?: string
          is_paid?: boolean
          name_en?: string | null
          name_fa: string
        }
        Update: {
          active?: boolean
          affects_balance?: boolean
          allow_half_day?: boolean
          allow_hourly?: boolean
          color?: string | null
          company_id?: string
          default_accrual_minutes_per_month?: number | null
          default_annual_cap_minutes?: number | null
          default_annual_quota_days?: number | null
          default_carryover_cap_minutes?: number
          id?: string
          is_paid?: boolean
          name_en?: string | null
          name_fa?: string
        }
        Relationships: [
          {
            foreignKeyName: "leave_types_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          active: boolean
          calendar_pref: string
          company_id: string
          created_at: string
          department_id: string | null
          employee_code: string
          full_name: string
          hire_date: string | null
          id: string
          job_title: string | null
          language_pref: string
          manager_id: string | null
          personnel_no: string | null
        }
        Insert: {
          active?: boolean
          calendar_pref?: string
          company_id: string
          created_at?: string
          department_id?: string | null
          employee_code: string
          full_name: string
          hire_date?: string | null
          id: string
          job_title?: string | null
          language_pref?: string
          manager_id?: string | null
          personnel_no?: string | null
        }
        Update: {
          active?: boolean
          calendar_pref?: string
          company_id?: string
          created_at?: string
          department_id?: string | null
          employee_code?: string
          full_name?: string
          hire_date?: string | null
          id?: string
          job_title?: string | null
          language_pref?: string
          manager_id?: string | null
          personnel_no?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_department_id_fkey"
            columns: ["department_id"]
            isOneToOne: false
            referencedRelation: "departments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_manager_id_fkey"
            columns: ["manager_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_roles: {
        Row: {
          id: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Insert: {
          id?: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Update: {
          id?: string
          role?: Database["public"]["Enums"]["app_role"]
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_roles_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      work_settings: {
        Row: {
          company_id: string
          hours_per_day: number
          id: string
          max_hourly_minutes_per_day: number
          updated_at: string
          updated_by: string | null
          weekend_days: number[]
          work_end: string
          work_start: string
        }
        Insert: {
          company_id: string
          hours_per_day?: number
          id?: string
          max_hourly_minutes_per_day?: number
          updated_at?: string
          updated_by?: string | null
          weekend_days?: number[]
          work_end?: string
          work_start?: string
        }
        Update: {
          company_id?: string
          hours_per_day?: number
          id?: string
          max_hourly_minutes_per_day?: number
          updated_at?: string
          updated_by?: string | null
          weekend_days?: number[]
          work_end?: string
          work_start?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_settings_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      team_leave_calendar: {
        Row: {
          day_part: Database["public"]["Enums"]["day_part"] | null
          department_id: string | null
          employee_id: string | null
          employee_name: string | null
          end_date: string | null
          end_time: string | null
          id: string | null
          leave_type_color: string | null
          leave_type_id: string | null
          leave_type_name_en: string | null
          leave_type_name_fa: string | null
          requested_minutes: number | null
          start_date: string | null
          start_time: string | null
          status: Database["public"]["Enums"]["leave_status"] | null
          unit: Database["public"]["Enums"]["leave_unit"] | null
        }
        Relationships: [
          {
            foreignKeyName: "leave_requests_employee_id_fkey"
            columns: ["employee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leave_requests_leave_type_id_fkey"
            columns: ["leave_type_id"]
            isOneToOne: false
            referencedRelation: "leave_types"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_department_id_fkey"
            columns: ["department_id"]
            isOneToOne: false
            referencedRelation: "departments"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      allocate_leave: {
        Args: {
          p_minutes: number
          p_employee_id: string
          p_leave_type_id: string
          p_period_end: string
          p_period_start: string
        }
        Returns: string
      }
      app_change_my_password: {
        Args: { p_current: string; p_new: string }
        Returns: undefined
      }
      app_bulk_create_employees: {
        Args: { p_company_id: string; p_rows: Json }
        Returns: Json
      }
      app_create_employee: {
        Args: {
          p_calendar_pref?: string
          p_company_id: string
          p_department_id?: string
          p_full_name: string
          p_hire_date?: string
          p_job_title?: string
          p_language_pref?: string
          p_manager_id?: string
          p_password: string
          p_personnel_no: string
          p_roles?: Database["public"]["Enums"]["app_role"][]
        }
        Returns: string
      }
      app_set_employee_password: {
        Args: { p_password: string; p_user_id: string }
        Returns: undefined
      }
      app_set_user_roles: {
        Args: {
          p_roles: Database["public"]["Enums"]["app_role"][]
          p_user_id: string
        }
        Returns: undefined
      }
      accrue_all_leave: { Args: never; Returns: Json }
      accrue_employee_leave: { Args: { p_employee_id: string }; Returns: undefined }
      accrue_leave: {
        Args: { p_employee_id: string; p_leave_type_id: string }
        Returns: number
      }
      accrue_my_leave: { Args: never; Returns: undefined }
      approve_leave_request: { Args: { p_id: string }; Returns: undefined }
      cancel_leave_request: { Args: { p_id: string }; Returns: undefined }
      compute_requested_minutes: {
        Args: {
          p_company_id: string
          p_day_part: Database["public"]["Enums"]["day_part"]
          p_end: string
          p_end_time?: string
          p_start: string
          p_start_time?: string
          p_unit?: Database["public"]["Enums"]["leave_unit"]
        }
        Returns: number
      }
      current_leave_balance: {
        Args: { p_employee_id: string; p_leave_type_id: string }
        Returns: number
      }
      get_my_cover_conflicts: {
        Args: { p_end: string; p_start: string }
        Returns: {
          employee_name: string
          end_date: string
          end_time: string | null
          request_id: string
          start_date: string
          start_time: string | null
          unit: Database["public"]["Enums"]["leave_unit"]
        }[]
      }
      get_replacement_candidates: {
        Args: {
          p_end: string
          p_end_time?: string
          p_start: string
          p_start_time?: string
          p_unit?: Database["public"]["Enums"]["leave_unit"]
        }
        Returns: {
          employee_code: string
          full_name: string
          profile_id: string
          unavailable: boolean
          unavailable_reason: string | null
        }[]
      }
      get_my_team_directory: {
        Args: never
        Returns: {
          department_name_en: string
          department_name_fa: string
          employee_code: string
          full_name: string
          manager_name: string
          profile_id: string
          relation: string
          roles: Database["public"]["Enums"]["app_role"][]
        }[]
      }
      jalali_month_of: {
        Args: { p_date: string }
        Returns: {
          gregorian_end: string
          gregorian_start: string
          jalali_month: number
          jalali_year: number
        }
      }
      submit_hourly_leave_request: {
        Args: {
          p_date: string
          p_end_time: string
          p_leave_type_id: string
          p_reason?: string
          p_start_time: string
        }
        Returns: string
      }
      set_employee_leave_policy: {
        Args: {
          p_accrual_minutes_per_month: number
          p_accrual_start_month: string
          p_annual_cap_minutes: number | null
          p_carryover_cap_minutes: number
          p_employee_id: string
          p_leave_type_id: string
        }
        Returns: string
      }
      reject_leave_request: {
        Args: { p_id: string; p_reason?: string }
        Returns: undefined
      }
      set_leave_balance: {
        Args: {
          p_employee_id: string
          p_leave_type_id: string
          p_target_minutes: number
        }
        Returns: number
      }
      submit_leave_request: {
        Args: {
          p_day_part: Database["public"]["Enums"]["day_part"]
          p_end: string
          p_leave_type_id: string
          p_reason?: string
          p_start: string
        }
        Returns: string
      }
    }
    Enums: {
      app_role: "admin" | "manager" | "employee" | "security"
      day_part: "full" | "am" | "pm"
      department_kind: "team" | "security" | "office"
      leave_unit: "day" | "hour"
      leave_status: "pending" | "approved" | "rejected" | "cancelled"
      ledger_entry:
        | "allocation"
        | "consumption"
        | "adjustment"
        | "reversal"
        | "carryover_forfeit"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: ["admin", "manager", "employee", "security"],
      day_part: ["full", "am", "pm"],
      department_kind: ["team", "security", "office"],
      leave_unit: ["day", "hour"],
      leave_status: ["pending", "approved", "rejected", "cancelled"],
      ledger_entry: [
        "allocation",
        "consumption",
        "adjustment",
        "reversal",
        "carryover_forfeit",
      ],
    },
  },
} as const
